app/routes/web.php
<?php

Auth::routes();

Route::post('/subscribe', 'SubscriberController@store')->name('subscribe.store');
Route::post('/tasks/delivered', 'TaskController@delivered')->name('tasks.delivered');
Route::post('/tasks/passed', 'TaskController@passed')->name('tasks.passed');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'SiteController@index')->name('sites.index');
    Route::post('/sites', 'SiteController@store')->name('sites.store');
    Route::get('/sites/create', 'SiteController@create')->name('sites.create');
    Route::put('/sites/{site}/update', 'SiteController@update')->name('sites.update');
    Route::get('/sites/{site}/show', 'SiteController@show')->name('sites.show');
    Route::delete('/sites/{site}', 'SiteController@destroy')->name('sites.destroy');
    Route::get('/sites/{site}/setting', 'SiteSettingController@index')->name('sites.setting');
    Route::get('/sites/setting/sw-file', 'SiteSettingController@downloadSwFile')->name('sites.sw-file');
    Route::get('/sites/{site}/stats', 'SiteController@stats')->name('sites.stats');

    Route::resources(['tasks' => 'TaskController']);
    Route::post('/tasks/count', 'TaskController@count')->name('tasks.count');
});

app/app/Http/Controllers/SiteController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Site;
use App\Entity\Subscriber;
use App\Helpers\ClearHttpForDomain;
use App\UseCases\Sites\SiteService;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Http\Request;
use Storage;

class SiteController extends Controller
{
    /**
     * @var SiteService
     */
    private $service;

    public function __construct(SiteService $service)
    {
        $this->service = $service;
    }

    public function index()
    {
        $sites = Site::withSubscriberCount()->paginate(10);
        return view('sites.index', compact('sites'));
    }

    public function create()
    {
        return view('sites.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'domain' => 'required|url',
            'image' => 'nullable|image'
        ]);

        $this->service->create($request['domain'], $request->file('image'));

        return redirect(route('sites.index'))->with('success', 'Site is created');
    }

    public function show(int $id)
    {
        $site = Site::withCount([
            'subscribers' => function (Builder $query) {
                $query->where('status', Subscriber::ACTIVE_STATUS);
            },
            'subscribers as subscribers_today' => function (Builder $query) {
                $query->whereDate('created_at', Carbon::today());
            },
            'subscribers as subscribers_denying' => function (Builder $query) {
                $query->where('status', Subscriber::COMPLETED_STATUS);
            }
        ])->findOrFail($id);

        return view('sites.show', compact('site'));
    }

    public function stats(int $siteId, Request $request)
    {
        $stats = $this->service->stats($siteId, $request->get('date'));

        return response()->json([
            'selectedMonth' => $stats->originDate->format('Y-m'),
            'months' => $stats->months,
            'chart' => [
                'labels' => $stats->days,
                'datasets' => [
                    [
                        'label' => 'Активное количество подписчиков',
                        'backgroundColor' => '#1e90ff',
                        'data' => $stats->subscriberActive,
                    ],
                    [
                        'label' => 'Количество отписок',
                        'backgroundColor' => '#cccccc',
                        'data' => $stats->subscriberCompleted,
                    ],
                    [
                        'label' => 'Количество подписчиков',
                        'backgroundColor' => '#f87979',
                        'data' => $stats->subscriberTotal,
                        'type' => 'line',
                        'fill' => false,
                        'showLine' => false,
                    ],
                ]
            ]
        ]);
    }

    public function update(Request $request, Site $site)
    {
        $this->validate($request, [
            'domain' => 'required|url',
            'image' => 'nullable|image|dimensions:min_width=128,min_height=128'
        ]);

        $site->update([
            'domain' => ClearHttpForDomain::clear($request['domain']),
            'image' => $request->file('image') ? $request->file('image')->store('sites/images', 'public') : null,
        ]);

        return redirect(route('sites.setting', $site))->with('success', 'Site is updated');
    }

    public function destroy(Site $site)
    {
        Storage::disk('public')->delete([$site->image, $site->script]);
        $site->delete();
        return redirect(route('sites.index'))->with('success', 'Site is deleted');
    }
}

app/resources/views/sites/create.blade.php
@extends('layouts.app')

@section('title', 'Добавление сайта')

@section('content')
    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <h1 class="title">
                Добавление сайта
            </h1>
        </div>
    </section>

    <form action="{{ route('sites.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="field">
            <label class="label" for="title">Домен</label>
            <div class="control">
                <input type="text" name="domain" class="input @error('domain') is-danger @enderror" id="title"
                       value="{{ old('domain') }}"
                       placeholder="https://domain.com">
            </div>
            @error('domain')
            <div class="help is-danger">{{ $message }}</div>
            @enderror
        </div>

        <div class="field">
            <label class="label" for="image">Картинка 128x128</label>
            <div class="file has-name is-boxed @error('image') is-danger @enderror">
                <label class="file-label">
                    <input id="image" class="file-input" type="file" name="image">
                    <span class="file-cta">
                                <span class="file-icon">
                                  <i class="fas fa-cloud-upload-alt"></i>
                                </span>
                                <span class="file-label">
                                  Картинка 128x128
                                </span>
                              </span>
                    <span class="file-name">
                      Выберите картинку
                    </span>
                    @error('image')
                    <div class="help is-danger">{{ $message }}</div>
                    @enderror
                </label>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button type="submit" class="button is-primary is-large">Следующий шаг</button>
            </div>
        </div>
    </form>
@endsection

@section('script')
    <script>

    </script>
@endsection

app/resources/views/sites/index.blade.php
@extends('layouts.app')

@section('content')
    @env('local')
        <button id="subscribe">Подписаться</button>
        <script src="{{ url('/subscribe.js') }}" async></script>
    @endenv

    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <div class="columns">
                <div class="column is-narrow">
                    <h1 class="title">
                        Мои сайты
                    </h1>
                </div>
                <div class="column">
                    <a href="{{ route('sites.create') }}" class="button is-primary">Добавить сайт</a>
                </div>
            </div>
        </div>
    </section>

    @foreach($sites as $site)
        <div class="box">
            <div class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <img src="{{ $site->image ? asset('storage/' . $site->image) : url('/images/128.png') }}">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content">
                        <a href="{{ route('sites.show', $site) }}">{{ $site->domain }}</a>
                        <p>Подписчиков: <strong>{{ $site->subscribers_count }}</strong></p>
                    </div>
                </div>
                <div class="media-right">
                    <form action="{{ route('sites.destroy', $site) }}" method="POST" onsubmit="return confirm('Вы уверены?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="delete"></button>
                    </form>
                </div>
            </div>
        </div>
    @endforeach

    {{ $sites->links('vendor.pagination.default') }}
@endsection

app/resources/views/sites/show.blade.php
@extends('layouts.app')

@section('title', $site->domain)

@section('content')
    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <div class="columns">
                <div class="column is-narrow">
                    <h1 class="title">
                        {{ $site->domain }}
                    </h1>
                </div>
                <div class="column">
                    <a href="{{ route('sites.setting', $site) }}" class="button is-primary">Настройка сайта</a>
                </div>
            </div>
        </div>
    </section>

    <chart :site='@json($site)'></chart>

    <section class="section">
        <div class="box">
            <nav class="level">
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Активные подписчики</p>
                        <p class="title">{{ $site->subscribers_count }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Подписчики за сегодня</p>
                        <p class="title">{{ $site->subscribers_today }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered">
                    <div>
                        <p class="heading">Количество отписок</p>
                        <p class="title">{{ $site->subscribers_denying }}</p>
                    </div>
                </div>
            </nav>
        </div>
    </section>
@endsection