app/routes/web.php
<?php

Auth::routes();

Route::post('/subscribe', 'SubscriberController@store')->name('subscribe.store');
Route::post('/tasks/delivered', 'TaskController@delivered')->name('tasks.delivered');
Route::post('/tasks/passed', 'TaskController@passed')->name('tasks.passed');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'SiteController@index')->name('sites.index');
    Route::post('/sites', 'SiteController@store')->name('sites.store');
    Route::get('/sites/create', 'SiteController@create')->name('sites.create');
    Route::put('/sites/{site}/update', 'SiteController@update')->name('sites.update');
    Route::get('/sites/{site}/show', 'SiteController@show')->name('sites.show');
    Route::delete('/sites/{site}', 'SiteController@destroy')->name('sites.destroy');
    Route::get('/sites/{site}/setting', 'SiteSettingController@index')->name('sites.setting');
    Route::get('/sites/setting/sw-file', 'SiteSettingController@downloadSwFile')->name('sites.sw-file');
    Route::get('/sites/{site}/stats', 'SiteController@stats')->name('sites.stats');

    Route::resources(['tasks' => 'TaskController']);
    Route::post('/tasks/count', 'TaskController@count')->name('tasks.count');
});

app/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use App\Entity\Browser;
use App\Entity\Country;
use App\Entity\Lang;
use App\Entity\Os;
use App\Entity\Site;
use App\Entity\Task;
use App\Entity\Variable;
use App\QueryBuilders\SubscribeQuery;
use App\UseCases\Tasks\DTO\Filter;
use App\UseCases\Tasks\DTO\Utm;
use App\UseCases\Tasks\TaskService;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use Redis;
use Storage;

class TaskController extends Controller
{
    /**
     * @var TaskService
     */
    private $service;

    public function __construct(TaskService $service)
    {
        $this->service = $service;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $query = Task::query();
        $sort = $request->get('sort') ?? 'asc';

        if (!empty($value = $request->get('title'))) {
            $query->where('title', 'like', '%' . $value . '%');
        }

        $tasks = $query->orderBy('created_at', $sort)->paginate(10);

        return view('tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $sites = Site::withSubscriberCount()->get();

        $browsers = Browser::pluck('name', 'id');
        $countries = Country::pluck('name', 'id');
        $os = Os::pluck('name', 'id');
        $languages = Lang::pluck('name', 'id');
        $variables = Variable::pluck('name', 'id');

        return view(
            'tasks.create',
            compact('sites', 'browsers', 'countries', 'os', 'languages', 'variables')
        );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'site_id' => 'nullable|integer',
            'title' => 'required',
            'text' => 'required',
            'url' => 'required',
            'image' => [
                Rule::requiredIf(empty($request['site_id'])),
                'image',
            ],
            'big_image' => 'nullable|image',
            'subscriber_count' => 'required|integer|min:1',
        ]);

        $task = $this->service->create(
            $request['site_id'],
            $request['title'],
            $request['text'],
            $request['url'],
            $request->file('image'),
            $request->file('big_image'),
            new Utm($request['utm_campaign']),
            new Filter(
                $request['site_id'],
                $request->input('filter_browser_id'),
                $request->input('filter_country_id'),
                $request->input('filter_language_id'),
                $request->input('filter_os_id'),
                $request->input('filter_variable_id')
            )
        );

        return redirect(route('tasks.show', $task));
    }

    /**
     * Display the specified resource.
     *
     * @param \App\Entity\Task $task
     * @return \Illuminate\Http\Response
     */
    public function show(Task $task)
    {
        return view('tasks.show', compact('task'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Entity\Task $task
     * @return \Illuminate\Http\Response
     */
    public function edit(Task $task)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \App\Entity\Task $task
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \App\Entity\Task $task
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Task $task)
    {
        Storage::disk('public')->delete($task->image);
        Storage::disk('public')->delete($task->big_image);
        Redis::del($task->getRedisKeys());
        $task->delete();
        return back()->with('success', 'Task is deleted');
    }

    public function count(Request $request)
    {
        $count = 0;
        $filter = new Filter(
            $request->json('site_id'),
            $request->json('browser_id'),
            $request->json('country_id'),
            $request->json('language_id'),
            $request->json('os_id'),
            $request->json('variable_id')
        );

        if ($filter->isNotEmpty()) {
            $count = SubscribeQuery::getQuery($filter)->count();
        }

        return response()->json([
            'count' => $count,
            'text' => trans_choice('segmentation.subscribers', $count)
        ]);
    }

    public function delivered(Request $request)
    {
        $task = Task::findOrFail($request->json('taskId'));
        $task->incrDeliveredCount();
        return response()->noContent();
    }

    public function passed(Request $request)
    {
        $task = Task::findOrFail($request->json('taskId'));
        $task->incrPassedCount();
        return response()->noContent();
    }
}

app/resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', 'Создание рассылки')

@section('content')
    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <h1 class="title">
                Создание рассылки
            </h1>
        </div>
    </section>

    @if(count($errors) > 0)
        <div class="notification is-danger">
            <button class="delete"></button>
            @foreach ($errors->all() as $error)
                <p>{{ $error }}</p>
            @endforeach
        </div>
    @endif

    <form action="{{ route('tasks.store') }}" method="POST" enctype="multipart/form-data">
        @csrf

        <div class="columns">

            <div class="column">
                <segmentation :sites='{{ $sites }}'
                              :browsers='@json($browsers)'
                              :countries='@json($countries)'
                              :languages='@json($languages)'
                              :os='@json($os)'
                              :variables='@json($variables)'
                        {{--                              :oldFields='@json(old())'--}}
                ></segmentation>

                <div class="field">
                    <label class="label" for="title">Заголовок</label>
                    <div class="control">
                        <input type="text" name="title" class="input @error('title') is-danger @enderror" id="title"
                               value="{{ old('title') }}"
                               placeholder="До 50 символов">
                    </div>
                    @error('title')
                    <div class="help is-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="field">
                    <label class="label" for="text">Текст уведомления</label>
                    <div class="control">
                        <textarea name="text" id="text" class="textarea @error('text') is-danger @enderror"
                                  rows="3"
                                  placeholder="До 125 символов">{{ old('text') }}</textarea>
                    </div>
                    @error('text')
                    <div class="help is-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="field">
                    <label class="label" for="url">Ссылка на уведомлении</label>
                    <div class="control">
                        <input id="url" type="text" name="url" class="input @error('url') is-danger @enderror"
                               value="{{ old('url') }}"
                               placeholder="https://example.com">
                    </div>
                    @error('url')
                    <div class="help is-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="field">
                    <label class="label" for="image">Картинка 128x128</label>
                    <div class="file has-name is-boxed @error('image') is-danger @enderror">
                        <label class="file-label">
                            <input id="image" class="file-input" type="file" name="image">
                            <span class="file-cta">
                                <span class="file-icon">
                                  <i class="fas fa-cloud-upload-alt"></i>
                                </span>
                                <span class="file-label">
                                    Картинка 128x128
                                </span>
                              </span>
                            <span class="file-name">Выберите картинку</span>
                        </label>
                    </div>
                </div>

            </div>

            <div class="column">

                <div class="column">
                    <p class="title is-4">Дополнительные опции</p>

                    <div class="field">
                        <label class="label" for="utm_campaign">UTM Campaign</label>
                        <div class="control">
                            <input id="utm_campaign" type="text" name="utm_campaign"
                                   class="input @error('utm_campaign') is-danger @enderror"
                                   value="{{ old('utm_campaign', '{utm_campaign}') }}">
                        </div>
                        @error('utm_campaign')
                        <div class="help is-danger">{{ $message }}</div>
                        @enderror
                    </div>

                    <div class="field">
                        <label class="label" for="big-image">Картинка 400x200</label>
                        <div class="file has-name is-boxed @error('big_image') is-danger @enderror">
                            <label class="file-label">
                                <input id="big-image" class="file-input" type="file" name="big_image">
                                <span class="file-cta">
                                <span class="file-icon">
                                  <i class="fas fa-cloud-upload-alt"></i>
                                </span>
                                <span class="file-label">
                                  Картинка 400x200
                                </span>
                              </span>
                                <span class="file-name">Выберите картинку</span>
                            </label>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        <div class="columns">
            <div class="column">
                <div class="field">
                    <div class="control">
                        <button type="submit" class="button is-primary is-large">Отправить</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
@endsection

app/resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', 'Мои рассылки')

@section('content')
    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <div class="columns">
                <div class="column is-narrow">
                    <h1 class="title">
                        Мои рассылки
                    </h1>
                </div>
                <div class="column">
                    <a href="{{ route('tasks.create') }}" class="button is-primary">Добавить рассылку</a>
                </div>
            </div>
        </div>
    </section>

    <section style="margin-bottom: 2rem;">
        <div class="box">
            <form action="?" method="GET">
                <div class="columns">
                    <div class="column is-four-fifths">
                        <div class="field is-horizontal">
                            <div class="field-body">
                                <div class="field">
                                    <p class="control is-expanded has-icons-left">
                                        <input class="input" name="title" type="text" placeholder="Заголовок"
                                               value="{{ request('title') }}">
                                        <span class="icon is-small is-left">
          <i class="fas fa-align-justify"></i>
        </span>
                                    </p>
                                </div>
                                <div class="field is-narrow">
                                    <input type="hidden" name="sort"
                                           value="{{ request('sort') === 'asc' || empty(request('sort')) ? 'desc' : 'asc' }}">
                                    <button class="button is-info" onclick="">
                                        @if(request('sort') === 'desc')
                                            <i class="fas fa-arrow-up"></i>
                                        @else
                                            <i class="fas fa-arrow-down"></i>
                                        @endif
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="column">
                        <div class="buttons">
                            <button type="submit" class="button is-success">Поиск</button>
                            <a href="?" class="button">Очистить</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </section>

    @foreach($tasks as $task)
        <div class="box">
            <div class="media">
                <figure class="media-left">
                    <p class="image is-128x128">
                        <img src="{{ $task->image ? asset('storage/' . $task->image) : url('/images/128.png') }}"
                             alt="">
                    </p>
                </figure>
                <div class="media-content">
                    <div class="content columns">
                        <div class="column">
                            <a href="{{ route('tasks.show', $task) }}">{{ $task->title }}</a>
                            <p>Отправлено {{ $task->created_at->format('d.m.Y H:i') }}</p>
                            <p>{{ $task->url }}</p>
                        </div>
                        <div class="level column" style="display: flex;">
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Количество</p>
                                    <p class="title">{{ $task->total_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Отправлено</p>
                                    <p class="title">{{ $task->sent_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Доставлено</p>
                                    <p class="title">{{ $task->delivered_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Переходов</p>
                                    <p class="title">{{ $task->passed_count }}</p>
                                </div>
                            </div>
                            <div class="level-item has-text-centered">
                                <div>
                                    <p class="heading">Отписок</p>
                                    <p class="title">{{ $task->deny_count }}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="media-right">
                    <form action="{{ route('tasks.destroy', $task) }}" method="POST"
                          onsubmit="return confirm('Вы уверены?')">
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="delete"></button>
                    </form>
                </div>
            </div>
        </div>
    @endforeach

    {{ $tasks->links('vendor.pagination.default') }}
@endsection

app/resources/views/tasks/show.blade.php
@extends('layouts.app')

@section('title', $task->title)

@section('content')
    <section class="hero">
        <div class="hero-body" style="padding-left: 0;">
            <div class="columns" style="align-items: center;">
                <div class="column is-narrow">
                    <h1 class="title">
                        {{ $task->title }}
                    </h1>
                </div>
                <div class="column">
                    <p>Отправлено: {{ $task->created_at->format('d.m.Y H:i') }}</p>
                </div>
            </div>
        </div>
    </section>

    <div class="columns">
        <div class="column is-narrow">
            <img src="{{ asset('storage/' . $task->image) }}" alt="{{ $task->title }}" width="128">
        </div>

        <div class="column">
            <div class="level">
                <div class="level-item has-text-centered is-justify-content-start">
                    <div>
                        <p class="heading">Количество</p>
                        <p class="title">{{ $task->total_count }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered is-justify-content-start">
                    <div>
                        <p class="heading">Отправлено</p>
                        <p class="title">{{ $task->sent_count }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered is-justify-content-start">
                    <div>
                        <p class="heading">Доставлено</p>
                        <p class="title">{{ $task->delivered_count }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered is-justify-content-start">
                    <div>
                        <p class="heading">Переходов</p>
                        <p class="title">{{ $task->passed_count }}</p>
                    </div>
                </div>
                <div class="level-item has-text-centered is-justify-content-start">
                    <div>
                        <p class="heading">Отписок</p>
                        <p class="title">{{ $task->deny_count }}</p>
                    </div>
                </div>
            </div>

            <table class="table">
                <tbody>
                <tr>
                    <td>Список получателей</td>
                    <td>{{ $task->site ? $task->site->domain : 'Все подписчики' }}</td>
                </tr>
                <tr>
                    <td>Заголовок</td>
                    <td>{{ $task->title }}</td>
                </tr>
                <tr>
                    <td>Текст</td>
                    <td>{{ $task->text }}</td>
                </tr>
                <tr>
                    <td>Ссылка</td>
                    <td>{{ $task->url }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
@endsection