app/routes/web.php
<?php

Auth::routes();

Route::post('/subscribe', 'SubscriberController@store')->name('subscribe.store');
Route::post('/tasks/delivered', 'TaskController@delivered')->name('tasks.delivered');
Route::post('/tasks/passed', 'TaskController@passed')->name('tasks.passed');

Route::middleware(['auth'])->group(function () {
    Route::get('/', 'SiteController@index')->name('sites.index');
    Route::post('/sites', 'SiteController@store')->name('sites.store');
    Route::get('/sites/create', 'SiteController@create')->name('sites.create');
    Route::put('/sites/{site}/update', 'SiteController@update')->name('sites.update');
    Route::get('/sites/{site}/show', 'SiteController@show')->name('sites.show');
    Route::delete('/sites/{site}', 'SiteController@destroy')->name('sites.destroy');
    Route::get('/sites/{site}/setting', 'SiteSettingController@index')->name('sites.setting');
    Route::get('/sites/setting/sw-file', 'SiteSettingController@downloadSwFile')->name('sites.sw-file');
    Route::get('/sites/{site}/stats', 'SiteController@stats')->name('sites.stats');

    Route::resources(['tasks' => 'TaskController']);
    Route::post('/tasks/count', 'TaskController@count')->name('tasks.count');
});

app/resources/views/layouts/partials/flash.blade.php
@if (session('success'))
    <div class="notification is-success">
        <button class="delete"></button>
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="notification is-danger">
        <button class="delete"></button>
        {{ session('error') }}
    </div>
@endif

@if (session('info'))
    <div class="notification is-info">
        <button class="delete"></button>
        {{ session('info') }}
    </div>
@endif

app/resources/views/layouts/partials/menu.blade.php
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="/">
            {{ config('app.name') }}
        </a>

        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
           data-target="navbarBasicExample">
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
            <span aria-hidden="true"></span>
        </a>
    </div>

    <div id="navbarBasicExample" class="navbar-menu">
        @if(auth()->check())
            <div class="navbar-start">
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" href="{{ route('tasks.index') }}">
                        Мои рассылки
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{ route('tasks.create') }}">
                            Создать рассылку
                        </a>
                    </div>
                </div>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link" href="{{ route('sites.index') }}">
                        Сайты
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{ route('sites.create') }}">
                            Добавить сайт
                        </a>
                    </div>
                </div>
            </div>
        @endif

        <div class="navbar-end">
            <div class="navbar-item">
                <div class="buttons">
                    @guest
                        <a class="button is-primary" href="{{ route('login') }}">
                            {{ __('Login') }}
                        </a>
                    @else
                        <a class="button is-light" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>

                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    @endguest
                </div>
            </div>
        </div>
    </div>
</nav>